# Generated by Django 5.1.6 on 2025-02-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_value', models.TextField()),
                ('source_value', models.TextField()),
                ('keyword', models.TextField()),
                ('quiz_content', models.TextField()),
                ('correct', models.TextField()),
                ('quiz_comment', models.TextField()),
                ('choices', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_value', models.TextField()),
                ('source_value', models.TextField()),
                ('period', models.IntegerField()),
                ('userKeyword', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('source_value', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('user', 'source_value', 'keyword')},
            },
        ),
    ]
