# Generated by Django 5.1.6 on 2025-02-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('keyword', models.TextField()),
                ('quiz_content', models.TextField()),
                ('correct', models.TextField()),
                ('choices', models.JSONField(default=list)),
            ],
        ),
    ]
