# Generated by Django 5.1.6 on 2025-02-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanBangBo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlydata',
            name='quiz_comment',
            field=models.TextField(default='no comment'),
            preserve_default=False,
        ),
    ]
