# Generated by Django 5.1.6 on 2025-02-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanBangBo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
