# Generated by Django 5.1.6 on 2025-02-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanBangBo', '0002_userchoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlydata',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recentlydata',
            name='source_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='source_value',
            field=models.CharField(max_length=255),
        ),
    ]
