# Generated by Django 5.1.6 on 2025-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanBangBo', '0002_recentlydata_quiz_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentlydata',
            old_name='type',
            new_name='source_value',
        ),
        migrations.AddField(
            model_name='recentlydata',
            name='type_value',
            field=models.TextField(default='헤럴드'),
            preserve_default=False,
        ),
    ]
