# Generated by Django 5.1.6 on 2025-02-27 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanBangBo', '0004_uservalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HanBangBo.uservalue'),
        ),
        migrations.AlterField(
            model_name='userkeyword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HanBangBo.uservalue'),
        ),
    ]
