# Generated by Django 5.1.6 on 2025-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanBangBo', '0005_alter_userchoice_user_alter_userkeyword_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservalue',
            name='assigned_value',
        ),
        migrations.AlterField(
            model_name='uservalue',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
