# Generated by Django 5.1.6 on 2025-02-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanBangBo', '0006_remove_uservalue_assigned_value_alter_uservalue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='source_type',
            field=models.CharField(default='언론사', max_length=255),
            preserve_default=False,
        ),
    ]
