name: Docker Image CI

on:
  push:
    branches: ["ci-test"]
  # pull_request:
  #   branches: ["ci-test"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build ./django/app --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/hanbangbo-back:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hanbangbo-back:latest
